config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :products
  root "products#index"

  post "checkout/create", to: 'checkout#create'
  
  resources :webhooks, only: [:create]

  post 'products/add_to_cart/:id', to: "products#add_to_cart", as: "add_to_cart"

  delete 'products/remove_from_cart/:id', to: "products#remove_from_cart", as: "remove_from_cart"

  get 'cart', to: "application#load_cart", as: "cart"

  get '/success', to: "checkout#success", as: "checkout_success"
  get '/failure', to: "checkout#failure", as: "checkout_failure"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    enum :status, {
        pending: 'pending',
        processing: 'processing',
        processed: 'processed',
        failed: 'failed'
    }, default: 'pending'
end

app/models/product.rb
class Product < ApplicationRecord
    validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :unit_price, presence: true, numericality: { greater_than: 0 }

    def to_s
        name
    end

    def total_price
        quantity * unit_price
    end

    def to_builder
        Jbuilder.new do |product|
            product.name
            product.price
        end
    end

    after_create do
        update(code: "#{self.id}_#{rand.to_s[2..10]}")
    end
end

app/models/user.rb
class User < ApplicationRecord

  # after_commit :create_paystack_customer, on: :create
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
    email
  end

  after_create do
    return if paystack_customer_id.present?

    paystack = Paystack.new(Rails.application.credentials[:paystack][:PAYSTACK_PUBLIC_KEY], Rails.application.credentials[:paystack][:PAYSTACK_PRIVATE_KEY])

    paystack_customers = PaystackCustomers.new(paystack)

    customer = paystack_customers.create( email: email )

    update(paystack_customer_id: customer['data']['customer_code'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :initialize_session
    before_action :load_cart
    before_action :load_paystack

    def load_cart
        @cart = Product.find(session[:cart])
        render 'carts/cart' if action_name == 'load_cart'
    end

    private

    def initialize_session
        session[:cart] ||= [] #empty cart = empty array
    end

    def load_paystack
        @paystack = Paystack.new(Rails.application.credentials[:paystack][:PAYSTACK_PUBLIC_KEY],Rails.application.credentials[:paystack][:PAYSTACK_PRIVATE_KEY])
    end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    
    def create
        total_amount = @cart.sum(&:total_price)
        cart_items = @cart.pluck(:name)
        reference = "#{@cart.pluck(:id).join().to_i}_#{rand.to_s[2..10]}"
        callback_url = checkout_success_url
        cancel_url = checkout_failure_url

        @payment = PaystackTransactions.new(@paystack)

        @result = @payment.initializeTransaction(
            :reference => reference,
            :amount => total_amount * 100,
            :email => current_user.email,
            callback_url: callback_url,
            channels: ["card"],
            metadata: {
                cancel_action: cancel_url,
                payment_medium: "Website",
                custom_fields: [
                    {
                        "display_name": "Cart Items",
                        "variable_name": "Cart Items",
                        "value": cart_items
                    }
                ]
            }
        )
        auth_url = @result['data']['authorization_url']
        respond_to do |format|
            format.html { redirect_to auth_url, allow_other_host: true }
        end
    end

    def success
        if params[:reference].present?
            session[:cart] = [] # empty array cart = empty array
            
            paystack = Paystack.new(Rails.application.credentials[:paystack][:PAYSTACK_PUBLIC_KEY], Rails.application.credentials[:paystack][:PAYSTACK_PRIVATE_KEY])

            transaction_reference = params[:reference]

            @transaction_result = PaystackTransactions.verify(paystack, transaction_reference)

            @cart_items = @transaction_result['data']['metadata']['custom_fields'].each do |field|
                field['value'].each do |name|
                    product = Product.find_by(name: name)
                    # product.increment!(:sales_count)
                end
            end
        else
            redirect_to checkout_failure_url, alert: "No info for you here."
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :unit_price, :quantity)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/cart.html.erb
<div class="container">
    <h1>Cart</h1>
    <hr>
    <% @cart.each do |product| %>
        <p><%= product.name %></p>
    <% end %>
    
    <% if @cart.present? %>
        <p>
            <%= @cart.pluck(:id) %>
            
            <%= @cart.collect { |item| item.to_builder.attributes! } %>

            <%= button_to "Buy now", checkout_create_path, data: { turbo: :false, turbo_submits_with: "Validating..." }, class: "btn btn-primary btn-sm" %>
        </p>
    <% end %>
</div>

app/views/checkout/failure.html.erb
<div class="container">
    <h1>Payment Cancelled</h1>
    
    <% if params[:reference].present? %>
    <div>
        <% paystack = Paystack.new(Rails.application.credentials[:paystack][:PAYSTACK_PUBLIC_KEY], Rails.application.credentials[:paystack][:PAYSTACK_PRIVATE_KEY]) %>

        <%# transaction_id = 3046924522 %>
        <% transaction_reference = params[:reference] %>
        <%# transactions = PaystackTransactions.new(paystack) %>
        <% result = PaystackTransactions.verify(paystack, transaction_reference) %>

        <%= result['data'] %>
        <hr>
        <%= result['data']['metadata']['custom_fields']['value'.to_i] %>
    </div>
    <% end %>
</div>

app/views/checkout/success.html.erb
<div class="container">
    <h1>Payment successfully made</h1>

    <p><b>Transaction status</b>: <%= @transaction_result['data']['status'] %></p>
    <p><b>Amount paid</b>: <%= number_to_currency((@transaction_result['data']['amount'])/100, unit: '') %> <%= @transaction_result['data']['currency'] %></p>

    <h2>You purchased</h2>

    <hr>

    <% @cart_items = @transaction_result['data']['metadata']['custom_fields'].each do |field| %>
        <ol>
            <% field['value'].each do |name| %>
                <li><%= name %></li>
            <% end %>
        </ol>
    <% end %>
    
    <% if params[:reference].present? %>
    <div>
        <% paystack = Paystack.new(Rails.application.credentials[:paystack][:PAYSTACK_PUBLIC_KEY], Rails.application.credentials[:paystack][:PAYSTACK_PRIVATE_KEY]) %>

        <% transaction_reference = params[:reference] %>
        <% @result = PaystackTransactions.verify(paystack, transaction_reference) %>

        <pre><%= JSON.pretty_generate(@result['data']) %></pre>

        <hr>

        <% @result['data']['metadata']['custom_fields'].each do |field| %>
            <% field['value'].each do |name| %>
                <% product = Product.find_by(name: name) %>
                <p><%= product.name %> **** <%= product.sales_count %> *** <%= product.price %></p>
            <% end %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaystackApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">

      <% if user_signed_in? %>
        <%= current_user.email %> | <%= current_user.paystack_customer_id if current_user.paystack_customer_id.present? %> | <%= link_to "Cart", cart_path %>(<%= @cart.count %>) | 
        <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete } %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>



      <hr>

      <p class="notice m-0"><%= notice %></p>
      <p class="alert p-0"><%= alert %></p>
      <%= link_to "All Products", products_path %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :unit_price, style: "display: block" %>
    <%= form.number_field :unit_price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(product.unit_price, unit: "₦") %>
  </p>

  <p>
    <strong>Sales count:</strong>
    <%= product.sales_count %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= product.code %>
  </p>

  <% if @cart.include?(product) %>
    <%= link_to "Remove from cart", remove_from_cart_path(product), data: {"turbo-method": :delete} %>
  <% else %>
    <%= link_to "Add to cart", add_to_cart_path(product), data: {"turbo-method": :post} %>
  <% end %>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>